# Remote Server for Microservice
remote_service:
  host: "http://ilo.eastvillagescl.com"
  port: 8094
  apikey: "xxxxxxxxxx"

# Local Server for Microservice
local_service:
  host: "localhost"
  port: 8094
  apikey: "xxxxxxxxxx"

logging:
 level : "verbose"